#!/usr/bin/env python3
"""build_app.py — assemble app/index.html from app/src/*.

The shipped app stays a single self-contained file (open it, no server) but is
EDITED as componentized sources (see app/src/README.md for the file map):
  app/src/shell.html          page structure, with three placeholders
  app/src/css/NN-*.css        CSS partials, concatenated in filename order
  app/src/js/NN-*.js          JS partials, concatenated in filename order
  app/src/embedded-graph.html generated by scripts/embed_demo.py

Run after editing any source:  python3 scripts/build_app.py
"""
import base64, mimetypes, os, re, sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "app", "src")
OUT = os.path.join(ROOT, "app", "index.html")


def read(name):
    with open(os.path.join(SRC, name), encoding="utf-8") as fh:
        return fh.read()


def read_dir(sub, ext):
    d = os.path.join(SRC, sub)
    names = sorted(n for n in os.listdir(d) if n.endswith(ext))
    assert names, f"no {ext} partials in app/src/{sub}/"
    return "".join(read(os.path.join(sub, n)) for n in names)


def version():
    """Single source of truth for the build version: the VERSION file at the repo
    root. Stamped into the header comment and the app footer so anyone can tell
    which build they are running (see CHANGELOG.md)."""
    path = os.path.join(ROOT, "VERSION")
    if not os.path.isfile(path):
        return "0.0.0-dev"
    with open(path, encoding="utf-8") as fh:
        return fh.read().strip() or "0.0.0-dev"


IMG_TOKEN = re.compile(r"__IMG:([A-Za-z0-9._-]+)__")


def inline_images(text):
    """Swap `__IMG:name__` for the data: URI of app/src/img/name.

    The app ships as one file you can e-mail, so a picture cannot be a second
    file next to it — and the page's CSP allows `data:` images and nothing
    remote. A missing file is not a build failure: the token becomes an empty
    string, the markup that uses it renders nothing, and the build says which
    file it was looking for.
    """
    d = os.path.join(SRC, "img")

    def sub(m):
        name = m.group(1)
        path = os.path.join(d, name)
        if not os.path.isfile(path):
            print(f"  ! missing image app/src/img/{name} — rendered as nothing")
            return ""
        mime = mimetypes.guess_type(name)[0] or "application/octet-stream"
        with open(path, "rb") as fh:
            b64 = base64.b64encode(fh.read()).decode("ascii")
        print(f"  + inlined app/src/img/{name} ({len(b64) // 1024} KB base64)")
        return f"data:{mime};base64,{b64}"

    return IMG_TOKEN.sub(sub, text)


def build():
    shell = read("shell.html")
    for ph, part in [("/*__STYLES__*/", read_dir("css", ".css")),
                     ("<!--__EMBEDDED__-->", read("embedded-graph.html")),
                     ("//__APP_JS__", read_dir("js", ".js"))]:
        part = part.rstrip("\n")
        assert shell.count(ph) == 1, f"placeholder {ph} missing in shell.html"
        shell = shell.replace(ph, part)
    shell = shell.replace("__VERSION__", version())
    shell = inline_images(shell)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(shell)
    return len(shell)


if __name__ == "__main__":
    n = build()
    print(f"Built app/index.html ({n:,} chars) from app/src/")
